apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-simple-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-simple-app
  template:
    metadata:
      labels:
        app: my-simple-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
